INSERT INTO CARRERAS (CARRERA_ID ,FECHA , NOMBRE) VALUES (1,'2020-07-17','Gran Carrera Global');

INSERT INTO COMPETIDORES (COMPETIDOR_ID ,NUMERO , NOMBRE ,CARRERA_ID ) VALUES (1,2,'Sebastian Loeb',1);
INSERT INTO COMPETIDORES (COMPETIDOR_ID ,NUMERO , NOMBRE ,CARRERA_ID ) VALUES (2,3,'Marcus Gronholm',1);
INSERT INTO COMPETIDORES (COMPETIDOR_ID ,NUMERO , NOMBRE ,CARRERA_ID) VALUES (3,7,'Carlos Sainz',1);
INSERT INTO COMPETIDORES (COMPETIDOR_ID ,NUMERO , NOMBRE ,CARRERA_ID) VALUES (4,11,'Petter Solberg',1);